Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    hello:
        docker:
            - image: cimg/node:17.2.0
        steps:
            - checkout
            - run:
                name: Hello World
                command: |
                    echo "Hello World"

workflows:
    my-workflow:
        job:
            - hello